// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0fnjXwZLF3S_tpPtbeXvwVC2KrSHJhBY',
    appId: '1:713529200883:web:72c7ab6886645413b22786',
    messagingSenderId: '713529200883',
    projectId: 'notifications-958c7',
    authDomain: 'notifications-958c7.firebaseapp.com',
    storageBucket: 'notifications-958c7.firebasestorage.app',
    measurementId: 'G-V62JBML8NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtGP0MxZTHAPb44Hcxn1ZYeLqCJA7jAVc',
    appId: '1:713529200883:android:947b5639fff587a5b22786',
    messagingSenderId: '713529200883',
    projectId: 'notifications-958c7',
    storageBucket: 'notifications-958c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqhhvQ0pjWhoPTOwRb4SWpeGAtdrX9HHE',
    appId: '1:713529200883:ios:ef158317d1b60b45b22786',
    messagingSenderId: '713529200883',
    projectId: 'notifications-958c7',
    storageBucket: 'notifications-958c7.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqhhvQ0pjWhoPTOwRb4SWpeGAtdrX9HHE',
    appId: '1:713529200883:ios:ef158317d1b60b45b22786',
    messagingSenderId: '713529200883',
    projectId: 'notifications-958c7',
    storageBucket: 'notifications-958c7.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0fnjXwZLF3S_tpPtbeXvwVC2KrSHJhBY',
    appId: '1:713529200883:web:a74230ab36c70e06b22786',
    messagingSenderId: '713529200883',
    projectId: 'notifications-958c7',
    authDomain: 'notifications-958c7.firebaseapp.com',
    storageBucket: 'notifications-958c7.firebasestorage.app',
    measurementId: 'G-K35GJPS86B',
  );

}